[icons]
icons = "material-nf"

[theme]
theme = "srcery"
[theme.overrides]
idle_fg = "#c0caf5"
idle_bg = "#0D1B2A"
good_fg = "#c0caf5"
good_bg = "#1C1C1C"
degraded_fg = "#e0af68"
bad_fg = "#f7768e"


[[block]]
block = "sound"
# NOTE:
# we could switch with
# pactl set-default-sink <name>
# the names can be retrieved along with id and description with
# pw-dump | jq '.[] | select(.type=="PipeWire:Interface:Node" and .info.props."media.class"=="Audio/Sink") | {id: .id, name: .info.props."node.name", description: .info.props."node.description"}'
# unfortunately chromium based apps ignore these commands

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|} $ip $device "

[[block]]
block = "load"
format = " $icon 1m: $1m.eng(w:4)"
interval = 1

[[block]]
block = "cpu"

[[block]]
block = "memory"
format = " $icon $mem_used $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90
# [[block]]
# block = "memory"
# [[block]]
# block = "memory"
# # Show swap if in use
# format = " $icon $swap_used.eng(range:1..) |"


[[block]]
block = "nvidia_gpu"

[[block]]
block = "disk_space"
warning = 500.0
alert = 200.0
alert_unit = "GB"

[[block]]
block = "disk_space"
path = "/mnt/storage/"
warning = 500.0
alert = 200.0
alert_unit = "GB"
error_format = ""      # not all my computers have this mounted

# TODO: add temperatures

# [[block]]
# block = "battery"
# device = "BAT1"
# format = "{percentage}% {state} {time}"
# full_format = "{percentage}%"
# show = "percentage"
# interval = 10

[[block]]
block = "time"
timezone = "UTC"
[block.format]
full = " $icon $timestamp.datetime(f:'%R %Z', l:es_ES) "
short = " $icon $timestamp.datetime(f:%R) "
[[block]]
block = "time"
timezone = "CET"
interval = 1
[block.format]
full = " $icon $timestamp.datetime(f:'%Y-%m-%d %R:%S %Z', l:es_ES) "
short = " $icon $timestamp.datetime(f:%R) "
