[shell]
bash_indicator = "BSH"
zsh_indicator = ""
disabled = false
[git_status]
conflicted = 'ğŸ³'
ahead = 'â‡¡${count}'
behind = 'â‡£${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
up_to_date = '[âœ“](bold green)'
untracked = '[?$count](blue)'
stashed = '[ğŸ“¦$count](yellow)'
modified = '[*$count](red)'
staged = '[+$count](green)'
renamed = '[>$count](green)'
deleted = '[-$count](red)'
